<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2jQ7elr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2jQ7elr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2jQ7elr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2jQ7elr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2jQ7elr\App_KernelDevDebugContainer([
    'container.build_hash' => '2jQ7elr',
    'container.build_id' => '808c2677',
    'container.build_time' => 1641779462,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2jQ7elr');
