<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFJCbxMI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFJCbxMI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFJCbxMI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFJCbxMI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFJCbxMI\App_KernelDevDebugContainer([
    'container.build_hash' => 'FJCbxMI',
    'container.build_id' => '016095b4',
    'container.build_time' => 1641676458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFJCbxMI');
