<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGpQZMVY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGpQZMVY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGpQZMVY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGpQZMVY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGpQZMVY\App_KernelDevDebugContainer([
    'container.build_hash' => 'GpQZMVY',
    'container.build_id' => '66cce299',
    'container.build_time' => 1641574857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGpQZMVY');
